export const api = {
    BLOG_LIST: "https://nazrul78.onrender.com/api/v1/blogs",
    BLOG_ADD: "https://nazrul78.onrender.com/api/v1/blog",
    BLOG_DELETE: "https://nazrul78.onrender.com/api/v1/blog/",
    BLOG_UPDATE: "https://nazrul78.onrender.com/api/v1/blog/",

    USER_LOGIN_API: "http://localhost:9092/api/v1/authenticate",
    USER_SIGNUP_API: "http://localhost:9092/api/v1/signup",
    USER_CREATE_API: "http://localhost:9092/api/v1/create/user",
    USER_LIST_ALL: "http://localhost:9092/api/v1/users",
    USER_DELETE: "http://localhost:9092/api/v1/user/",
    USER_INACTIVE: "http://localhost:9092/api/v1/inactive/users",
    USER_ACTIVATE: "http://localhost:9092/api/v1/active/user/",
    USER_UPDATE: "http://localhost:9092/api/v1/user/",
    USER_PASSWORD_UPDATE: "http://localhost:9092/api/v1/user/password/",
    USER_GET_SINGLE: "http://localhost:9092/api/v1/user/by/token",

    BUILDINGS_GET_ALL_API: "http://localhost:9092/api/v1/buildings",
    BUILDINGS_CREATE_API: "http://localhost:9092/api/v1/building",
    BUILDINGS_GET_SINGLE_API: "http://localhost:9092/api/v1/building/",
    BUILDINGS_UPDATE: "http://localhost:9092/api/v1/building/",
    BUILDINGS_DELETE: "http://localhost:9092/api/v1/building/",

    RENTERS_LIST: "http://localhost:9092/api/v1/renters",
    RENTERS_LIST_SIMPLE: "http://localhost:9092/api/v1/renters/simple",
    RENTERS_LIST_SIMPLE_BY_USER_ID: "http://localhost:9092/api/v1/renters/user/",
    RENTERS_CREATE: "http://localhost:9092/api/v1/renter",
    RENTERS_SINGLE: "http://localhost:9092/api/v1/renter/",
    RENTERS_DELETE: "http://localhost:9092/api/v1/renter",

    RENT_PAYMENT_CREATE: 'http://localhost:9092/api/v1/payment',
    RENT_PAYMENT_GET_ALL: 'http://localhost:9092/api/v1/payments',
    RENT_PAYMENT_GET_ALL_BY_USER_ID: 'http://localhost:9092/api/v1/payments/user/',
    RENT_PAYMENT_DELETE: 'http://localhost:9092/api/v1/payment/',
}